import { WA0178 } from './products/WA0178/WA0178'
import { WA0179 } from './products/WA0179'
import { WA0190 } from './products/WA0190/WA0190'
import { WA0194 } from './products/WA0194'
import { WA0198 } from './products/WA0198'
import { WA0197 } from './products/WA0197'
import { WA0462 } from './products/WA0462'
import { WA0466 } from './products/WA0466'
import { WA0789 } from './products/WA0789'
import { WA0810 } from './products/WA0810'
import { WA0950 } from './products/WA0950'
import { WA0952 } from './products/WA0952'
import { WA0953 } from './products/WA0953'
import { WA3551_3 } from './products/WA3551.3'
import { WA3553_3 } from './products/WA3553.3'
import { WA0860 } from './products/WA0860/WA0178'
import { WA0862 } from './products/WA0862'
import { WA0863 } from './products/WA0863'
import { WA0864 } from './products/WA0864'
import { WA0865 } from './products/WA0865'
import { WA0870 } from './products/WA0870'
import { WA0892 } from './products/WA0892'
import { WR130E } from './products/WR130E'
import { WR141E } from './products/WR141E'
import { WR165E } from './products/WR165E'
import { WR167E } from './products/WR167E'
import { WR147E_1 } from './products/WR147E.1'
import { WR155E } from './products/WR155E'
import { WA0004_1 } from './products/WA0004.1'
import { WA0142 } from './products/WA0142'
import { WA0220 } from './products/WA0220'
import { WA0222 } from './products/WA0222'
import { WA0223 } from './products/WA0223'
import { WA0307 } from './products/WA0307'
import { WA0308 } from './products/WA0308'
import { WA1820 } from './products/WA1820'
import { WA1821 } from './products/WA1821'
import { WA1843 } from './products/WA1843'
import { WA4015 } from './products/WA4015'
import { WA4036 } from './products/WA4036'
import { WA4037 } from './products/WA4037'
import { WA4050 } from './products/WA4050'
import { WA4038 } from './products/WA4038'
import { WA4039 } from './products/WA4039'
import { WA4042 } from './products/WA4042'
import { WA4048 } from './products/WA4048'
import { WA4301 } from './products/WA4301'
import { WA3551 } from './products/WA3551'
import { WA3553 } from './products/WA3553'
import { WA3553_2 } from './products/WA3553_2'
import { WA3014 } from './products/WA3014'
import { WA3014_2 } from './products/WA3014_2'
import { WA3641 } from './products/WA3641'
import { WA3648 } from './products/WA3648'
import { WA3601 } from './products/WA3601'
import { WA3610 } from './products/WA3610'
import { WA3611 } from './products/WA3611'
import { WA3867 } from './products/WA3867'
import { WA3883 } from './products/WA3883'
import { WG157E_9 } from './products/WG157E_9'
import { WG183E_9 } from './products/WG183E_9'
import { WG184E_9 } from './products/WG184E_9'
import { WG908E_9 } from './products/WG908E_9'
import { WG908E } from './products/WG908E'
import { WG894E_9 } from './products/WG894E_9'
import { WG894E } from './products/WG894E'
import { WG801E_91 } from './products/WG801E_91'
import { WG801E_5 } from './products/WG801E_5'
import { WG761E } from './products/WG761E'
import { WG779E } from './products/WG779E'
import { WG743E } from './products/WG743E'
import { WG730E } from './products/WG730E'
import { WG330E_9 } from './products/WG330E_9'
import { WG330E } from './products/WG330E'
import { WG284E_9 } from './products/WG284E_9'
import { WG260E_9 } from './products/WG260E_9'
import { WG252E } from './products/WG252E'
import { WG252E_9 } from './products/WG252E_9'
import { WG585E_9 } from './products/WG585E_9'
import { WG572E } from './products/WG572E'
import { WG543E_9 } from './products/WG543E_9'
import { WG543E } from './products/WG543E'
import { WG620E } from './products/WG620E'
import { WG620E_2 } from './products/WG620E_2'
import { WG620E_9 } from './products/WG620E_9'
import { WG630E_9 } from './products/WG630E_9'
import { WG441E_9 } from './products/WG441E_9'
import { WG583E_9 } from './products/WG583E_9'
import { WG630E } from './products/WG630E'
import { WG324E } from './products/WG324E'
import { WG322E_9 } from './products/WG322E_9'
import { WG324E_9 } from './products/WG324E_9'
import { WG349E_9 } from './products/WG349E_9'
import { WG381E_9 } from './products/WG381E_9'
import { WG385E_9 } from './products/WG385E_9'
import { WG261E_9 } from './products/WG261E_9'
import { WG829E_9 } from './products/WG829E_9'
import { WG163_9 } from './products/WG163E_9'

export const CATEGORIES = [
  {
    active: '1',
    cover: 'https://bitec.okoiagency.com/img/c/10.jpg',
    date_add: '2020-04-12 16:33:29',
    date_upd: '2021-03-25 12:21:25',
    description: '',
    doNotRegenerateNTree: false,
    force_id: false,
    groupBox: null,
    id: 10,
    id_category: '10',
    id_category_default: null,
    id_image: 10,
    id_parent: '2',
    id_shop_default: '1',
    is_root_category: '0',
    level_depth: '2',
    link_rewrite: 'robot-cortacesped-landroid',
    meta_description: '',
    meta_keywords: '',
    meta_title: '',
    name: 'ROBOT CORTACÉSPED LANDROID',
    position: '0',
    subcategories: [
      {
        id: 11,
        id_category: '11',
        name: 'El Landroid es único',
        active: '1',
        position: '0',
        description: '',
        id_parent: '10',
        id_category_default: null,
        level_depth: '3',
        nleft: '4',
        nright: '5',
        link_rewrite: 'el-landroid-es-unico',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2020-04-12 16:40:28',
        date_upd: '2021-05-07 09:11:14',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 11,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/10/11/11_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/11.jpg',
        compare: require('../../assets/img/cat/10/11/compare.jpg'),
        products: [
          {
            tax_name: 'deprecated',
            tax_rate: 0,
            id_manufacturer: '0',
            id_supplier: '0',
            id_category_default: '11',
            id_shop_default: '1',
            manufacturer_name: false,
            supplier_name: false,
            name: 'Descubre Landroid. El robot más inteligente del mercado',
            description: '',
            description_short: '',
            quantity: 0,
            minimal_quantity: '1',
            low_stock_threshold: null,
            low_stock_alert: '0',
            available_now: '',
            available_later: '',
            price: 0,
            specificPrice: [],
            additional_shipping_cost: '0.00',
            wholesale_price: '0.000000',
            on_sale: '0',
            online_only: '0',
            unity: '',
            unit_price: 0,
            unit_price_ratio: '0.000000',
            ecotax: '0.000000',
            reference: '',
            supplier_reference: '',
            location: '',
            width: '0.000000',
            height: '0.000000',
            depth: '0.000000',
            weight: '0.000000',
            ean13: '',
            isbn: '',
            upc: '',
            link_rewrite: 'video-presentacion',
            meta_description: '',
            meta_keywords: '',
            meta_title: '',
            quantity_discount: '0',
            customizable: '0',
            new: false,
            uploadable_files: '0',
            text_fields: '0',
            active: '1',
            redirect_type: '301-category',
            id_type_redirected: '0',
            available_for_order: '1',
            available_date: '0000-00-00',
            show_condition: '0',
            condition: 'new',
            show_price: '1',
            indexed: '1',
            visibility: 'both',
            date_add: '2020-04-12 22:43:36',
            date_upd: '2021-03-23 13:01:01',
            tags: false,
            state: '1',
            base_price: '0.000000',
            id_tax_rules_group: '0',
            id_color_default: 0,
            advanced_stock_management: '0',
            out_of_stock: 1,
            depends_on_stock: false,
            isFullyLoaded: 1,
            cache_is_pack: '0',
            cache_has_attachments: '0',
            is_virtual: '1',
            id_pack_product_attribute: null,
            cache_default_attribute: '0',
            category: 'el-landroid-es-unico',
            pack_stock_type: '3',
            additional_delivery_times: '1',
            delivery_in_stock: '',
            delivery_out_stock: '',
            id: 25,
            id_shop_list: [],
            force_id: false,
            cover: {
              id_image: '330'
            },
            compare: 'https://bitec.okoiagency.com/img/c/11.jpg',
            accesories: [],
            especifications: [],
            images: [
              {
                cover: '1',
                id_image: '330',
                legend: '',
                position: '1',
                url: require('./videos/1.jpg'),
                url_bolb: {}
              }
            ],
            url: 'ms-appx:///25.mp4',
            compare_25: {},
            video_blob: {}
          },
          {
            tax_name: 'deprecated',
            tax_rate: 0,
            id_manufacturer: '0',
            id_supplier: '0',
            id_category_default: '11',
            id_shop_default: '1',
            manufacturer_name: false,
            supplier_name: false,
            name: 'Corta lo más cerca del borde con Cut to Edge',
            description: '',
            description_short: 'Los modelos M y L de Landroid incorporan un sistema de corte con una posición especial de las cuchillas, permitiendo cortar lo más cerca posible del borde.',
            quantity: 0,
            minimal_quantity: '1',
            low_stock_threshold: null,
            low_stock_alert: '0',
            available_now: '',
            available_later: '',
            price: 0,
            specificPrice: [],
            additional_shipping_cost: '0.00',
            wholesale_price: '0.000000',
            on_sale: '0',
            online_only: '0',
            unity: '',
            unit_price: 0,
            unit_price_ratio: '0.000000',
            ecotax: '0.000000',
            reference: '',
            supplier_reference: '',
            location: '',
            width: '0.000000',
            height: '0.000000',
            depth: '0.000000',
            weight: '0.000000',
            ean13: '',
            isbn: '',
            upc: '',
            link_rewrite: 'video-presentacion',
            meta_description: '',
            meta_keywords: '',
            meta_title: '',
            quantity_discount: '0',
            customizable: '0',
            new: false,
            uploadable_files: '0',
            text_fields: '0',
            active: '1',
            redirect_type: '301-category',
            id_type_redirected: '0',
            available_for_order: '1',
            available_date: '0000-00-00',
            show_condition: '0',
            condition: 'new',
            show_price: '1',
            indexed: '1',
            visibility: 'both',
            date_add: '2020-04-12 22:43:57',
            date_upd: '2021-05-18 12:28:38',
            tags: false,
            state: '1',
            base_price: '0.000000',
            id_tax_rules_group: '0',
            id_color_default: 0,
            advanced_stock_management: '0',
            out_of_stock: 2,
            depends_on_stock: false,
            isFullyLoaded: 1,
            cache_is_pack: '0',
            cache_has_attachments: '0',
            is_virtual: '1',
            id_pack_product_attribute: null,
            cache_default_attribute: '0',
            category: 'el-landroid-es-unico',
            pack_stock_type: '3',
            additional_delivery_times: '1',
            delivery_in_stock: '',
            delivery_out_stock: '',
            id: 26,
            id_shop_list: [],
            force_id: false,
            cover: {
              id_image: '337'
            },
            compare: 'https://bitec.okoiagency.com/img/c/11.jpg',
            accesories: [],
            especifications: [],
            images: [
              {
                cover: '1',
                id_image: '337',
                legend: '',
                position: '1',
                url: require('./videos/2.jpg'),
                url_bolb: {}
              }
            ],
            url: 'ms-appx:///26.mp4',
            compare_26: {},
            video_blob: {}
          },
          {
            tax_name: 'deprecated',
            tax_rate: 0,
            id_manufacturer: '0',
            id_supplier: '0',
            id_category_default: '11',
            id_shop_default: '1',
            manufacturer_name: false,
            supplier_name: false,
            name: 'Comparte la batería con todas tus herramientas de PowerShare',
            description: '',
            description_short: 'La batería Landroid sirve para cualquier herramienta Worx 20V. Sácala de la robot, colócala en la herramienta que necesites y listo.',
            quantity: 0,
            minimal_quantity: '1',
            low_stock_threshold: null,
            low_stock_alert: '0',
            available_now: '',
            available_later: '',
            price: 0,
            specificPrice: [],
            additional_shipping_cost: '0.00',
            wholesale_price: '0.000000',
            on_sale: '0',
            online_only: '0',
            unity: '',
            unit_price: 0,
            unit_price_ratio: '0.000000',
            ecotax: '0.000000',
            reference: '',
            supplier_reference: '',
            location: '',
            width: '0.000000',
            height: '0.000000',
            depth: '0.000000',
            weight: '0.000000',
            ean13: '',
            isbn: '',
            upc: '',
            link_rewrite: 'video-presentacion',
            meta_description: '',
            meta_keywords: '',
            meta_title: '',
            quantity_discount: '0',
            customizable: '0',
            new: false,
            uploadable_files: '0',
            text_fields: '0',
            active: '1',
            redirect_type: '301-category',
            id_type_redirected: '0',
            available_for_order: '1',
            available_date: '0000-00-00',
            show_condition: '0',
            condition: 'new',
            show_price: '1',
            indexed: '1',
            visibility: 'both',
            date_add: '2020-04-12 22:44:09',
            date_upd: '2021-05-18 12:27:52',
            tags: false,
            state: '1',
            base_price: '0.000000',
            id_tax_rules_group: '0',
            id_color_default: 0,
            advanced_stock_management: '0',
            out_of_stock: 2,
            depends_on_stock: false,
            isFullyLoaded: 1,
            cache_is_pack: '0',
            cache_has_attachments: '0',
            is_virtual: '1',
            id_pack_product_attribute: null,
            cache_default_attribute: '0',
            category: 'el-landroid-es-unico',
            pack_stock_type: '3',
            additional_delivery_times: '1',
            delivery_in_stock: '',
            delivery_out_stock: '',
            id: 27,
            id_shop_list: [],
            force_id: false,
            cover: {
              id_image: '339'
            },
            compare: 'https://bitec.okoiagency.com/img/c/11.jpg',
            accesories: [],
            especifications: [],
            images: [
              {
                cover: '1',
                id_image: '339',
                legend: '',
                position: '1',
                url: require('./videos/3.jpg'),
                url_bolb: {}
              }
            ],
            url: 'ms-appx:///27.mp4',
            compare_27: {},
            video_blob: {}
          },
          {
            tax_name: 'deprecated',
            tax_rate: 0,
            id_manufacturer: '0',
            id_supplier: '0',
            id_category_default: '11',
            id_shop_default: '1',
            manufacturer_name: false,
            supplier_name: false,
            name: '¿Quieres personalizar tu Landroid?',
            description: '',
            description_short: 'Configurable según tus necesidades\n',
            quantity: 0,
            minimal_quantity: '1',
            low_stock_threshold: null,
            low_stock_alert: '0',
            available_now: '',
            available_later: '',
            price: 0,
            specificPrice: [],
            additional_shipping_cost: '0.00',
            wholesale_price: '0.000000',
            on_sale: '0',
            online_only: '0',
            unity: '',
            unit_price: 0,
            unit_price_ratio: '0.000000',
            ecotax: '0.000000',
            reference: '',
            supplier_reference: '',
            location: '',
            width: '0.000000',
            height: '0.000000',
            depth: '0.000000',
            weight: '0.000000',
            ean13: '',
            isbn: '',
            upc: '',
            link_rewrite: 'video-presentacion',
            meta_description: '',
            meta_keywords: '',
            meta_title: '',
            quantity_discount: '0',
            customizable: '0',
            new: false,
            uploadable_files: '0',
            text_fields: '0',
            active: '1',
            redirect_type: '301-category',
            id_type_redirected: '0',
            available_for_order: '1',
            available_date: '0000-00-00',
            show_condition: '0',
            condition: 'new',
            show_price: '1',
            indexed: '1',
            visibility: 'both',
            date_add: '2020-04-12 22:44:22',
            date_upd: '2021-05-18 12:26:59',
            tags: false,
            state: '1',
            base_price: '0.000000',
            id_tax_rules_group: '0',
            id_color_default: 0,
            advanced_stock_management: '0',
            out_of_stock: 2,
            depends_on_stock: false,
            isFullyLoaded: 1,
            cache_is_pack: '0',
            cache_has_attachments: '0',
            is_virtual: '1',
            id_pack_product_attribute: null,
            cache_default_attribute: '0',
            category: 'el-landroid-es-unico',
            pack_stock_type: '3',
            additional_delivery_times: '1',
            delivery_in_stock: '',
            delivery_out_stock: '',
            id: 28,
            id_shop_list: [],
            force_id: false,
            cover: {
              id_image: '331'
            },
            compare: 'https://bitec.okoiagency.com/img/c/11.jpg',
            accesories: [],
            especifications: [],
            images: [
              {
                cover: '1',
                id_image: '331',
                legend: '',
                position: '1',
                url: require('./videos/4.jpg'),
                url_bolb: {}
              }
            ],
            url: 'ms-appx:///28.mp4',
            compare_28: {},
            video_blob: {}
          },
          {
            tax_name: 'deprecated',
            tax_rate: 0,
            id_manufacturer: '0',
            id_supplier: '0',
            id_category_default: '11',
            id_shop_default: '1',
            manufacturer_name: false,
            supplier_name: false,
            name: '¿Qué hace que el Landroid sea único? Descubre AIA',
            description: '',
            description_short: 'La tecnología patentada AIA ofrece dos prestaciones únicas: Landroid cubre un mayor área de corte que otros robots y corta en zonas estrechas y de difícil acceso.',
            quantity: 0,
            minimal_quantity: '1',
            low_stock_threshold: null,
            low_stock_alert: '0',
            available_now: '',
            available_later: '',
            price: 0,
            specificPrice: [],
            additional_shipping_cost: '0.00',
            wholesale_price: '0.000000',
            on_sale: '0',
            online_only: '0',
            unity: '',
            unit_price: 0,
            unit_price_ratio: '0.000000',
            ecotax: '0.000000',
            reference: '',
            supplier_reference: '',
            location: '',
            width: '0.000000',
            height: '0.000000',
            depth: '0.000000',
            weight: '0.000000',
            ean13: '',
            isbn: '',
            upc: '',
            link_rewrite: 'video-presentacion',
            meta_description: '',
            meta_keywords: '',
            meta_title: '',
            quantity_discount: '0',
            customizable: '0',
            new: false,
            uploadable_files: '0',
            text_fields: '0',
            active: '1',
            redirect_type: '301-category',
            id_type_redirected: '0',
            available_for_order: '1',
            available_date: '0000-00-00',
            show_condition: '0',
            condition: 'new',
            show_price: '1',
            indexed: '1',
            visibility: 'both',
            date_add: '2020-05-03 11:30:20',
            date_upd: '2021-05-18 12:29:21',
            tags: false,
            state: '1',
            base_price: '0.000000',
            id_tax_rules_group: '0',
            id_color_default: 0,
            advanced_stock_management: '0',
            out_of_stock: 2,
            depends_on_stock: false,
            isFullyLoaded: 1,
            cache_is_pack: '0',
            cache_has_attachments: '0',
            is_virtual: '1',
            id_pack_product_attribute: null,
            cache_default_attribute: '0',
            category: 'el-landroid-es-unico',
            pack_stock_type: '3',
            additional_delivery_times: '1',
            delivery_in_stock: '',
            delivery_out_stock: '',
            id: 41,
            id_shop_list: [],
            force_id: false,
            cover: {
              id_image: '381'
            },
            compare: 'https://bitec.okoiagency.com/img/c/11.jpg',
            accesories: [],
            especifications: [],
            images: [
              {
                cover: '1',
                id_image: '381',
                legend: '',
                position: '1',
                url: require('./videos/5.jpg'),
                url_bolb: {}
              }
            ],
            url: 'ms-appx:///41.mp4',
            compare_41: {},
            video_blob: {}
          },
          {
            tax_name: 'deprecated',
            tax_rate: 0,
            id_manufacturer: '0',
            id_supplier: '0',
            id_category_default: '11',
            id_shop_default: '1',
            manufacturer_name: false,
            supplier_name: false,
            name: '¿Sabes cómo instalar tu Landroid?',
            description: '',
            description_short: 'Poner a punto tu robot Landroid nunca ha sido tan sencillo, además siempre que lo necesites puedes ponerte en contacto con nosotros para que te ayudemos.',
            quantity: 0,
            minimal_quantity: '1',
            low_stock_threshold: null,
            low_stock_alert: '0',
            available_now: '',
            available_later: '',
            price: 0,
            specificPrice: [],
            additional_shipping_cost: '0.00',
            wholesale_price: '0.000000',
            on_sale: '0',
            online_only: '0',
            unity: '',
            unit_price: 0,
            unit_price_ratio: '0.000000',
            ecotax: '0.000000',
            reference: '',
            supplier_reference: '',
            location: '',
            width: '0.000000',
            height: '0.000000',
            depth: '0.000000',
            weight: '0.000000',
            ean13: '',
            isbn: '',
            upc: '',
            link_rewrite: 'video-presentacion',
            meta_description: '',
            meta_keywords: '',
            meta_title: '',
            quantity_discount: '0',
            customizable: '0',
            new: false,
            uploadable_files: '0',
            text_fields: '0',
            active: '1',
            redirect_type: '301-category',
            id_type_redirected: '0',
            available_for_order: '1',
            available_date: '0000-00-00',
            show_condition: '0',
            condition: 'new',
            show_price: '1',
            indexed: '1',
            visibility: 'both',
            date_add: '2020-11-18 11:30:31',
            date_upd: '2021-05-18 12:27:26',
            tags: false,
            state: '1',
            base_price: '0.000000',
            id_tax_rules_group: '0',
            id_color_default: 0,
            advanced_stock_management: '0',
            out_of_stock: 2,
            depends_on_stock: false,
            isFullyLoaded: 1,
            cache_is_pack: '0',
            cache_has_attachments: '0',
            is_virtual: '1',
            id_pack_product_attribute: null,
            cache_default_attribute: '0',
            category: 'el-landroid-es-unico',
            pack_stock_type: '3',
            additional_delivery_times: '1',
            delivery_in_stock: '',
            delivery_out_stock: '',
            id: 45,
            id_shop_list: [],
            force_id: false,
            cover: {
              id_image: '383'
            },
            compare: 'https://bitec.okoiagency.com/img/c/11.jpg',
            accesories: [],
            especifications: [],
            images: [
              {
                cover: '1',
                id_image: '373',
                legend: '',
                position: '1',
                url: require('./videos/6.jpg'),
                url_bolb: {}
              }
            ],
            url: 'ms-appx:///45.mp4',
            compare_45: {},
            video_blob: {}
          }
        ],
        miniatura_url: {}
      },
      {
        id: 29,
        id_category: '29',
        name: 'ROBOTS',
        active: '1',
        position: '3',
        description: '',
        id_parent: '10',
        id_category_default: null,
        level_depth: '3',
        nleft: '10',
        nright: '11',
        link_rewrite: 'robots',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 20:12:33',
        date_upd: '2021-05-07 09:07:19',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 29,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/10/29/29_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/11.jpg',
        compare: require('../../assets/img/cat/10/11/compare.jpg'),

        products: [
          WR130E,
          WR141E,
          WR165E,
          WR167E,
          WR147E_1,
          WR155E
        ]
      },

      {
        id: 929,
        id_category: '929',
        name: 'Modulos de presonalización',
        active: '1',
        position: '3',
        description: '',
        id_parent: '10',
        id_category_default: null,
        level_depth: '3',
        nleft: '10',
        nright: '11',
        link_rewrite: 'robots',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 20:12:33',
        date_upd: '2021-05-07 09:07:19',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 29,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/10/929/929_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/11.jpg',
        compare: require('../../assets/img/cat/10/11/compare.jpg'),

        products: [WA0860, WA0862, WA0863, WA0864, WA0865, WA0870, WA0892],
        miniatura_url: {}
      },

      {
        id: 930,
        id_category: '9230',
        name: 'Accesorios Landroid',
        active: '1',
        position: '3',
        description: '',
        id_parent: '10',
        id_category_default: null,
        level_depth: '3',
        nleft: '10',
        nright: '11',
        link_rewrite: 'robots',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 20:12:33',
        date_upd: '2021-05-07 09:07:19',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 29,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/10/930/930_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/11.jpg',
        compare: require('../../assets/img/cat/10/11/compare.jpg'),
        products: [WA0178, WA0179, WA0190, WA0194, WA0197, WA0198, WA0462, WA0466, WA0789, WA0810, WA0950, WA0952, WA0953, WA3551_3, WA3553_3],
        miniatura_url: {}
      }

    ]
  },
  {
    id: 14,
    id_category: '14',
    name: 'HERRAMIENTAS DE JARDÍN',
    active: '1',
    position: '1',
    description: '',
    id_parent: '2',
    id_category_default: null,
    level_depth: '2',
    nleft: '13',
    nright: '30',
    link_rewrite: 'herramientas-de-jardin',
    meta_title: '',
    meta_keywords: '',
    meta_description: '',
    date_add: '2020-05-28 20:57:44',
    date_upd: '2021-04-12 11:43:33',
    is_root_category: '0',
    id_shop_default: '1',
    groupBox: null,
    doNotRegenerateNTree: false,
    id_image: false,
    id_shop_list: [],
    force_id: false,
    subcategories: [
      {
        id: 19,
        id_category: '19',
        name: 'Cortabordes',
        active: '1',
        position: '0',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '14',
        nright: '15',
        link_rewrite: 'cortabordes',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-01-27 09:16:05',
        date_upd: '2021-04-20 08:56:04',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 19,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/19/19_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/19.jpg',
        compare: require('../../assets/img/cat/14/19/compare.jpg'),
        products: [WG157E_9, WG163_9, WG183E_9, WG184E_9],

        miniatura_url: {}
      },
      {
        id: 27,
        id_category: '27',
        name: 'DESBROZADORA',
        active: '1',
        position: '1',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '16',
        nright: '17',
        link_rewrite: 'desbrozadora',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 20:12:26',
        date_upd: '2021-04-20 09:06:00',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: false,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/27/27_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/27.jpg',
        compare: require('../../assets/img/cat/14/27/compare.jpg'),

        products: [
          {
            tax_name: 'deprecated',
            tax_rate: 21,
            id_manufacturer: '0',
            id_supplier: '0',
            id_category_default: '27',
            id_shop_default: '1',
            manufacturer_name: false,
            supplier_name: false,
            name: 'Desbrozadora Nitro 40V',
            description: 'Modelo sin baterías ni cargador',
            description_short: '',
            quantity: 0,
            minimal_quantity: '1',
            low_stock_threshold: null,
            low_stock_alert: '0',
            available_now: '',
            available_later: '',
            price: 0,
            specificPrice: [],
            additional_shipping_cost: '0.00',
            wholesale_price: '0.000000',
            on_sale: '0',
            online_only: '0',
            unity: '',
            unit_price: 0,
            unit_price_ratio: '0.000000',
            ecotax: '0.000000',
            reference: 'WG186E.92',
            supplier_reference: '',
            location: '',
            width: '0.000000',
            height: '0.000000',
            depth: '0.000000',
            weight: '0.000000',
            ean13: '82877596',
            isbn: '',
            upc: '',
            link_rewrite: 'herramienta-multifuncion-jardin-n20-40v-220v-s-bat-incluye-cortabordes-y-desbrozadora',
            meta_description: '',
            meta_keywords: '',
            meta_title: '',
            quantity_discount: '0',
            customizable: '0',
            new: false,
            uploadable_files: '0',
            text_fields: '0',
            active: '1',
            redirect_type: '301-category',
            id_type_redirected: '0',
            available_for_order: '1',
            available_date: '0000-00-00',
            show_condition: '0',
            condition: 'new',
            show_price: '1',
            indexed: '1',
            visibility: 'both',
            date_add: '2021-02-19 20:12:26',
            date_upd: '2021-04-27 16:11:10',
            tags: false,
            state: '1',
            base_price: '0.000000',
            id_tax_rules_group: '1',
            id_color_default: 0,
            advanced_stock_management: '0',
            out_of_stock: 0,
            depends_on_stock: false,
            isFullyLoaded: 1,
            cache_is_pack: '0',
            cache_has_attachments: '0',
            is_virtual: '0',
            id_pack_product_attribute: null,
            cache_default_attribute: '0',
            category: 'desbrozadora',
            pack_stock_type: '3',
            additional_delivery_times: '1',
            delivery_in_stock: '',
            delivery_out_stock: '',
            id: 92,
            id_shop_list: [],
            force_id: false,
            cover: {
              id_image: '390'
            },
            compare: 'https://bitec.okoiagency.com/img/c/27.jpg',
            features: [

              {
                id_feature: null,
                position: '5',
                id_lang: '1',
                name: 'Batería',
                id_feature_value: null,
                custom: '0',
                value: '40V (2*20V) no incluidas',
                id_product: null
              },
              {
                id_feature: '10',
                position: '14',
                id_lang: '1',
                name: 'Velocidad en vacio',
                id_feature_value: '200',
                custom: '0',
                value: '5500-6200 rpm',
                id_product: '92'
              },
              {
                id_feature: null,
                position: '25',
                id_lang: '1',
                name: 'Diámetro del hilo de corte',
                id_feature_value: null,
                custom: '0',
                value: '2*2,4mm',
                id_product: null
              },
              {
                id_feature: '60',
                position: '60',
                id_lang: '1',
                name: 'Ancho de corte cuchilla desbrozadora',
                id_feature_value: '198',
                custom: '0',
                value: '25cm',
                id_product: '92'
              },
              {
                id_feature: '61',
                position: '61',
                id_lang: '1',
                name: 'Ancho de corte hilo cortabordes',
                id_feature_value: '199',
                custom: '0',
                value: '38cm',
                id_product: '92'
              },
              {
                id_feature: null,
                position: '11',
                id_lang: '1',
                name: 'Peso',
                id_feature_value: null,
                custom: '0',
                value: '4.1kg',
                id_product: null
              }
            ],
            accesories: [
              {
                name: '1',
                value: 'Carrete de hilo',
                id_bitecaccesories: '2264'
              },
              {
                name: '1',
                value: 'Cuchilla desbrozadora',
                id_bitecaccesories: '2265'
              },
              {
                name: '1',
                value: 'Arnés',
                id_bitecaccesories: '2266'
              }
            ],
            especifications: [
              {
                id_especificacion: '5707',
                id_product: '92',
                data: 'Alimentado por dos baterías de 20V que suministran gran potencia y tiempo de funcionamiento'
              },
              {
                id_especificacion: '5708',
                id_product: '92',
                data: 'Motor Brushless (sin escobillas), que proporciona mayor potencia, autonomía y vida útil de la máquina'
              },
              {
                id_especificacion: '5709',
                id_product: '92',
                data: 'Diseño para enganchar diferentes cabezales'
              },
              {
                id_especificacion: '5710',
                id_product: '92',
                data: 'Multiherramienta profesional de alta resistencia para condiciones de trabajo difíciles'
              },
              {
                id_especificacion: '5711',
                id_product: '92',
                data: 'Ajuste de velocidad alta / baja con control de aceleración de velocidad variable'
              },
              {
                id_especificacion: '5712',
                id_product: '92',
                data: 'Sistema de alimentación automática del hilo, presionando el cortabordes contra la superficie'
              },
              {
                id_especificacion: '5713',
                id_product: '92',
                data: 'Indicador de nivel de carga de la batería'
              },
              {
                id_especificacion: '5714',
                id_product: '92',
                data: 'El cargador de doble puerto puede cargar 2 baterías al mismo tiempo'
              },
              {
                id_especificacion: '5715',
                id_product: '92',
                data: 'Plataforma Powershare. Batería extraíble e intercambiable con todas las herramientas eléctricas y de jardín de la gama 20V de Worx'
              },
              {
                id_especificacion: '5716',
                id_product: '92',
                data: 'No incluye batería ni cargador'
              }
            ],
            images: [
              {
                cover: '1',
                id_image: '390',
                legend: '',
                position: '1',
                url: require('./products/WG186E_92/1.jpg'),
                url_bolb: {}
              },
              {
                cover: null,
                id_image: '382',
                legend: '',
                position: '2',
                url: require('./products/WG186E_92/2.jpg'),
                url_bolb: {}
              },
              {
                cover: null,
                id_image: '272',
                legend: '',
                position: '3',
                url: require('./products/WG186E_92/3.jpg'),
                url_bolb: {}
              },
              {
                cover: null,
                id_image: '273',
                legend: '',
                position: '4',
                url: require('./products/WG186E_92/4.jpg'),
                url_bolb: {}
              }
            ],
            url: false,
            compare_92: {},
            video_blob: {}
          }
        ],
        miniatura_url: {}
      },
      {
        id: 21,
        id_category: '21',
        name: 'Cortasetos',
        active: '1',
        position: '2',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '18',
        nright: '19',
        link_rewrite: 'cortasetos',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-01-27 09:16:26',
        date_upd: '2021-04-20 10:01:42',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 21,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/21/21_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/21.jpg',
        compare: require('../../assets/img/cat/14/21/compare.jpg'),
        products: [WG801E_5, WG801E_91, WG260E_9, WG261E_9, WG284E_9, WG252E, WG252E_9, WG261E_9, WG908E, WG908E_9],

        miniatura_url: {}
      },
      {
        id: 22,
        id_category: '22',
        name: 'Motosierras',
        active: '1',
        position: '3',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '20',
        nright: '21',
        link_rewrite: 'motosierras',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-01-27 09:16:37',
        date_upd: '2021-04-20 10:06:29',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 22,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/22/22_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/22.jpg',
        compare: require('../../assets/img/cat/14/22/compare.jpg'),
        products: [WG322E_9, WG324E, WG324E_9, WG349E_9, WG381E_9, WG385E_9, WG894E, WG894E_9, WG908E, WG908E_9],

        miniatura_url: {}
      },
      {
        id: 23,
        id_category: '23',
        name: 'Sopladores',
        active: '1',
        position: '4',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '22',
        nright: '23',
        link_rewrite: 'sopladores',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-01-27 09:16:47',
        date_upd: '2021-04-20 10:07:09',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 23,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/23/23_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/23.jpg',
        compare: require('../../assets/img/cat/14/23/compare.jpg'),
        products: [WG543E, WG543E_9, WG583E_9, WG585E_9, WG572E],

        miniatura_url: {}
      },
      {
        id: 28,
        id_category: '28',
        name: 'HYDROSHOT',
        active: '1',
        position: '5',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '24',
        nright: '25',
        link_rewrite: 'hydroshot',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 20:12:30',
        date_upd: '2021-04-20 10:12:00',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 28,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/28/28_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/28.jpg',
        compare: require('../../assets/img/cat/14/28/compare.jpg'),
        products: [WG620E, WG620E_2, WG620E_9, WG630E, WG630E_9],

        miniatura_url: {}
      },
      {
        id: 20,
        id_category: '20',
        name: 'Cortacésped',
        active: '1',
        position: '6',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '26',
        nright: '27',
        link_rewrite: 'cortacesped',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-01-27 09:16:16',
        date_upd: '2021-04-20 10:11:38',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: 20,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/20/20_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/20.jpg',
        compare: require('../../assets/img/cat/14/20/compare.jpg'),
        products: [WG730E, WG779E, WG743E, WG761E],
        miniatura_url: {}
      },
      {
        id: 26,
        id_category: '26',
        name: 'ACCESORIOS',
        active: '1',
        position: '7',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '28',
        nright: '29',
        link_rewrite: 'Accesorios',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 19:36:02',
        date_upd: '2021-04-20 10:07:35',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: false,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/26/26_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/26.jpg',

        products: [WA0004_1, WA0142, WA0220, WA0222, WA0223, WA0307, WA0308, WA1820, WA1821, WA1843, WA4015, WA4036, WA4037, WA4038, WA4039, WA4042, WA4048, WA4050, WA4301],
        miniatura_url: {}
      },
      {
        id: 1026,
        id_category: '1026',
        name: 'BATERÍAS Y CARGADORES',
        active: '1',
        position: '7',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '28',
        nright: '29',
        link_rewrite: 'Accesorios',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 19:36:02',
        date_upd: '2021-04-20 10:07:35',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: false,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/1026/1026_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/26.jpg',

        products: [WA3551, WA3553, WA3553_2, WA3014, WA3014_2, WA3641, WA3648, WA3601, WA3610, WA3611, WA3867, WA3883],
        miniatura_url: {}
      },
      {
        id: 1027,
        id_category: '1026',
        name: 'VARIOS',
        active: '1',
        position: '7',
        description: '',
        id_parent: '14',
        id_category_default: null,
        level_depth: '3',
        nleft: '28',
        nright: '29',
        link_rewrite: 'Accesorios',
        meta_title: '',
        meta_keywords: '',
        meta_description: '',
        date_add: '2021-02-19 19:36:02',
        date_upd: '2021-04-20 10:07:35',
        is_root_category: '0',
        id_shop_default: '1',
        groupBox: null,
        doNotRegenerateNTree: false,
        id_image: false,
        id_shop_list: [],
        force_id: false,
        miniatura: require('../../assets/img/cat/14/1027/1027_thumb.jpg'),
        cover: 'https://bitec.okoiagency.com/img/c/26.jpg',

        products: [WG441E_9, WG330E, WG330E_9, WG829E_9],
        miniatura_url: {}
      }

    ]
  }
]
