export const WA0220 =                      {
    "tax_name": "deprecated",
    "tax_rate": 21,
    "id_manufacturer": "0",
    "id_supplier": "0",
    "id_category_default": "29",
    "id_shop_default": "1",
    "manufacturer_name": false,
    "supplier_name": false,
    "name": "Cabezal cortasetos pértiga ",
    "description": "Compatible con desbrozadora Nitro WG186E",
    "description_short": "Compatible con desbrozadora Nitro WG186E",
    "quantity": 0,
    "minimal_quantity": "1",
    "low_stock_threshold": null,
    "low_stock_alert": "0",
    "available_now": "",
    "available_later": "",
    "price": 0,
    "specificPrice": [],
    "additional_shipping_cost": "0.00",
    "wholesale_price": "0.000000",
    "on_sale": "0",
    "online_only": "0",
    "unity": "",
    "unit_price": 0,
    "unit_price_ratio": "0.000000",
    "ecotax": "0.000000",
    "reference": "WA0221",
    "supplier_reference": "",
    "location": "",
    "width": "0.000000",
    "height": "0.000000",
    "depth": "0.000000",
    "weight": "0.000000",
    "ean13": "82877607",
    "isbn": "",
    "upc": "",
    "link_rewrite": "robot-cortacesped-landroid-m700-plus-wifi",
    "meta_description": "",
    "meta_keywords": "",
    "meta_title": "",
    "quantity_discount": "0",
    "customizable": "0",
    "new": false,
    "uploadable_files": "0",
    "text_fields": "0",
    "active": "1",
    "redirect_type": "301-category",
    "id_type_redirected": "0",
    "available_for_order": "1",
    "available_date": "0000-00-00",
    "show_condition": "0",
    "condition": "new",
    "show_price": "1",
    "indexed": "1",
    "visibility": "both",
    "date_add": "2021-02-19 20:12:33",
    "date_upd": "2021-05-21 10:57:25",
    "tags": false,
    "state": "1",
    "base_price": "0.000000",
    "id_tax_rules_group": "1",
    "id_color_default": 0,
    "advanced_stock_management": "0",
    "out_of_stock": 0,
    "depends_on_stock": false,
    "isFullyLoaded": 1,
    "cache_is_pack": "0",
    "cache_has_attachments": "0",
    "is_virtual": "0",
    "id_pack_product_attribute": null,
    "cache_default_attribute": "0",
    "category": "robots",
    "pack_stock_type": "3",
    "additional_delivery_times": "1",
    "delivery_in_stock": "",
    "delivery_out_stock": "",
    "id": 131,
    "id_shop_list": [],
    "force_id": false,
    "cover": {
        "id_image": "431"
    },
    "compare": "https://bitec.okoiagency.com/img/c/29.jpg",
    "features": [
        {
            "id_feature": "19",
            "position": "22",
            "id_lang": "1",
            "name": "Longitud de la espada",
            "id_feature_value": "266",
            "custom": "0",
            "value": "45cm",
            "id_product": "113"
        },
        {
            "id_feature": "19",
            "position": "22",
            "id_lang": "1",
            "name": "Longitud de corte",
            "id_feature_value": "266",
            "custom": "0",
            "value": "43cm",
            "id_product": "113"
        },
        {
            "id_feature": "19",
            "position": "22",
            "id_lang": "1",
            "name": "Diámetro de corte",
            "id_feature_value": "266",
            "custom": "0",
            "value": "24mm",
            "id_product": "113"
        },
        {
            "id_feature": "19",
            "position": "22",
            "id_lang": "1",
            "name": "Acción de doble corte",
            "id_feature_value": "266",
            "custom": "0",
            "value": "Sí",
            "id_product": "113"
        },
        {
            "id_feature": "19",
            "position": "22",
            "id_lang": "1",
            "name": "Máx. altura de corte",
            "id_feature_value": "266",
            "custom": "0",
            "value": "3m",
            "id_product": "113"
        },
        {
            "id_feature": "19",
            "position": "22",
            "id_lang": "1",
            "name": "Peso",
            "id_feature_value": "266",
            "custom": "0",
            "value": "2,1kg",
            "id_product": "113"
        },
    ],
    "accesories": [

    ],
    "especifications": [
        {
            "id_especificacion": "6094",
            "id_product": "131",
            "data": "Compatible con desbrozadora Nitro WG186E"
        },
      
    ],
    "images": [
        {
            "cover": "1",
            "id_image": "427",
            "legend": "",
            "position": "1",
            "url": require('./1.jpg'),
            "url_bolb": {}
        },

    ],
    "url": false,
    "compare_131": {},
    "video_blob": {}
}